name: HW1 CI

on: push

jobs:
  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_HW3_HANDLERS_CONFIG: "handlers.conf"
        envkey_HW3_EXCEPTIONS_LOG: "exceptions.log"
        file_name: .env
        fail_on_empty: false
  buildAndTest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, build, test
      run: |
        npm install
        npm run build
        npm test
      env:
        CI: true